version: 2
jobs:
  build:
    docker:
      - image: buhman/chicken:levo
    steps:
      - checkout
      - run:
          name: build modules
          command: |
            chicken-install -n
      - run:
          name: run tests
          command: |
            csi tests/run.scm
